#!/bin/bash

curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost
curl http://localhost